### ISSUE TITLE
User Manual: Add this instruction to avoid errors

### ISSUE THREAD

**Issue by malayangbiblia** [rubiot/ibiblia#14]
I think I found my source of errors. Sorry about that. I get an error result along the way whenever I do this:

1. Replace my destination file with an updated file (newly exported).
2. I associate a word from the source to an already tagged (w/strongs) word on my destination verse.

So next time around users should never do No. 2 whenever they do No. 1.

**Comment by rubiot** [comment]
I don't see how the No. 1 would be related to No 2. This issue might be solely related to the fact that your destination verse does have strongs. This is an untested scenario for iBiblia. Do you think you could strip these tags?

**Comment by malayangbiblia** [comment]
The tags were created using iBiblia. The errors occur if and only if I redo the associations on the existing strongs tags w/o associations. Its only needed to build the associations table but if the associations from the old tags are clear, no error occurs. But the strongs are still there.

**Comment by rubiot** [comment]
I'm at a loss here. The expected workflow should be the following:

1. Create a new project selecting a source text **having strongs** and a destination text **with no strongs**.
2. Associate/Link words from source text to their translation in destination text. This action will not add any tags to the destination text at all. The project only saves the association between words from both texts.
3. At any time you can export your work to a theWord bible module file. Because you've told which words translate which ones, iBiblia knows which tags to borrow from the source text. This operation (export) won't make any changes to the project. Your destination text will remain without any tags. Again, only the linkage you create between both texts is kept.

So, now I ask: Why does your destination text has any strong tags, other than the ones that existed in the imported bible module at project creation time? Have you manually added tags to your destination text, or reimported the text using the project properties? You should never have to do this.

**Comment by malayangbiblia** [comment]
About the destination file, I actually removed my previous strongs tags and started from no strongs tags, but for some reason which I now forgot, I re-imported what I exported previously (which had all the strong tags I've done in iBiblia). Yes, I get you. I should never have done that which gives me another idea to avoid this since I didn't see this warning in the first place in the wiki. What if you put that in the wiki or a pop-up warning when importing saying, "destination file should have such and such a format or else you will encounter an error."
