### ISSUE TITLE
Exporting incomplete tagging

### ISSUE THREAD

**Issue by malayangbiblia** [rubiot/ibiblia#4]
Hey Rubio,

Thanks for everything man. You make my ministry very doable. Bless you more!
I tried the export to dictionary/concordance and it seems its not working yet. Can it export properly even for incomplete taggings since my work isn't done yet? 

Bro. Edmund

**Comment by rubiot** [comment]
Hello, Bro. Edmund, this should work. What happens when you click the export button and choose a file?

**Comment by rubiot** [comment]
I did some tests using the project you've sent me and it's working OK **except** for two problems:

1. The strongs that already were on your destination text don't get exported. This is because the concordance is generated based on the associations (and you didn't associate anything for these verses). You'll have to associate these verses.

2. The concordance properties are not translated to English. I'm fixing this right now and I release the update later.

**Comment by malayangbiblia** [comment]
> 
> 
> Hello, Bro. Edmund, this should work. What happens when you click the export button and choose a file?

I haven't tried this again yet, but I will if you need to know if the error still exists.

**Comment by malayangbiblia** [comment]
> 
> 
> I did some tests using the project you've sent me and it's working OK **except** for two problems:
> 
>     1. The strongs that already were on your destination text don't get exported. This is because the concordance is generated based on the associations (and you didn't associate anything for these verses). You'll have to associate these verses.
> 
>     
Alright. I have a couple of questions:
1. What happens to the associations if I replace my destination file with the last exported bible file?
2. Is there another way to determine the association other than when it highlights the words?

**Comment by rubiot** [comment]
1. Associations are created **only** when you link word(s) from the source and destination text using the mouse. Adding <WGxx> tags to the destination text won't help, because iBiblia don't understand them. Does that clarify you question?
2. Associated words are displayed in black, non-associated ones are displayed in gray. If you're having trouble distinguishing between black and gray fonts, you can try to increase your fonts.

**Comment by rubiot** [comment]
I understand this is not a bug. Can you confirm that?

**Comment by malayangbiblia** [comment]
> 
> 
> Hello, Bro. Edmund, this should work. What happens when you click the export button and choose a file?

This is working ok when theWord is not running.

**Comment by rubiot** [comment]
OK. The new release now handles this problem. Instead of crashing it now gives a warning remembering the user to check if the file is being used by theWord.
