### ISSUE TITLE
Auto associated words won't stick

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#48]
Ok. I just used this feature today after all this time. The reason was that I accidentally broke my association from Genesis 1 to 3 after a mistake I made with iBibliaMerge. So what's happening is, whenever I push auto associate, I see the association but these are the things that happen:
1. Strongs count remain "0" on the destination file.
2. When I proceed to the next verse (right green arrow) and go back to previous verses( left green arrow), the associations are not there anymore.

**Comment by rubiot** [comment]
This is a known problem (#3). Suggestions are not saved unless you make at least one manual association. I'll prioritize this fix.

**Comment by rubiot** [comment]
I remember now, this was intentional, I've included this rule because if you leave auto-associate on and start navigating it'll associate remaining words without you even noticing. I see two options here:

1. Ask the user if he wants to keep the automatic changes when he tries to navigate;
2. Create an option to toggle this rule on/off.

**Comment by openbibles** [comment]
Thank Bro. this is a big help for creating Interlinears.

**Comment by openbibles** [comment]
> 
> 
> This is a known problem (#3). Suggestions are not saved unless you make at least one manual association. I'll prioritize this fix.

Good think you mentioned this, at least it works 99% of the time, I just need to manually associate a word which happens almost all the time.

**Comment by openbibles** [comment]
The work around is as good as it gets for me.
