### ISSUE TITLE
Dictionary Pop up using ctrl+mouse hover: feature enhancement suggestion

### ISSUE THREAD

**Issue by malayangbiblia** [rubiot/ibiblia#6]
It's a little annoying/unproductive when associating words between two texts using the ctrl key since the key is associated with 1st - the pop up dictionary and 2nd to select/associate multiple words. Reason being is that even if I turn on the press ctrl key for pop up dict, the pop-up executes right after the words have been associated in multiple words association. I suggest that instead of using ctr click only, why not use ctrl+right click to turn on pop up dictionary? or which ever you think is best.

**Comment by rubiot** [comment]
Hm. I consider using some other shortcut to activate the popop. I remember having this problem too, but I must have used a different workflow, because this wasn't that frequent. I guess it's because I've always used a Greek text as the source text, so the need to associate multiple words on the source text was rare.

**Comment by malayangbiblia** [comment]
KJV NT has almost double the amount of english words compared to the Greek and so should be the Tagalog plus the fact that I'm using dynamic equivalence translation so this feature is very useful.

**Comment by rubiot** [comment]
Modifying key changed to Alt. Please check the new release.
