### ISSUE TITLE
"Associated" Status Toggle

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#60]
The Status Feature is great for checking/auditing association work, but when I replace the source text, there are verses that seem to default to "Needs Review" even if the verse association is completed, those I had set to "Associated". 

I think it would be more efficient if we make iBiblia auto-assign the "Associated" status based on the Strong's counts. It goes something like this:

If Destination Strong's Count = Source Strong's Count, then iBiblia sets the Status to "Associated" automatically. Otherwise, it's set to "Not associated" or "Needs Review."

I cannot remember myself setting the status to other options aside from the "Associated." If I'm not done with a verse I never touch the status. Only time I use it is when I'm done with a verse. I hope this can be automated as well. 

Just like the other features, you can make this as an option under the options menu.

This will also be helpful to compensate for #2  which can trigger anytime. I just had 11 chapters (13 to 24) of Genesis wiped almost completely after a source text update. My only way of checking the affected verses is the status' colors but sadly, they are like 50% inaccurate. 

Thanks for everything, bro!

**Comment by rubiot** [comment]
This was by design, assuming that the try-and-keep-associations feature was unreliable. I guess it is now more reliable, so maybe I can leave the status untouched now.

I think I said this before, but I supposed that replacing a text would be a feature to be used sparingly and with much caution, but I guess I was wrong, seeing that you have been using it as just another part of your workflow. And thanks to your heavy use of the feature it is better and much more trustworthy now. But I don't think it can be perfect and cover all cases. For instance, if you have "word1 word2" and you change it to "word2 word1 word2", the associations from the original "word2" will be migrated to the first "word2", which may not be what one would want. There can be another cases like this, but I guess you'd be the best person to assess that.

**Comment by openbibles** [comment]
Well, I'm not talking about the tiny imperfections. As a matter of fact, the thing was consistently keeping 100% of the associations of untouched verses right after the text update not until the latest release. There could be something that got broke when you tried to fix #55. It's like this.
![image](https://user-images.githubusercontent.com/46296587/58681947-4b6e3d80-83a1-11e9-9488-4b1eb9caba9e.png)
![image](https://user-images.githubusercontent.com/46296587/58681961-5aed8680-83a1-11e9-9065-20943a85b7f9.png)
All affected verses are like these. I think the auto-associated words are the ones that were gone and these remaining associated words are the ones I manually associated. Hmmm..

**Comment by openbibles** [comment]
Is there a hotkey to apply this status instead of using the mouse?

**Comment by openbibles** [comment]
I just realize something I did that most probably caused the wiping of 11 chapters of verse association! I remember that I did a massive replacement of my source text on the LXX just before that problem occurred. So its not iBiblia but me! Sorry for the trouble, bro!

**Comment by rubiot** [comment]
Please check the [new release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.60), now iBiblia keep association status untouched when you replace a text.

Yes, there is hotkeys for changing the status - use the numeric keys 1 to 4.

**Comment by openbibles** [comment]
Awesome!
