### ISSUE TITLE
Handle line-breaks in verse edit when pasting from clipboard

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#80]
Hi Rubio,

Hope you're doing good. Just like to report this persistent error. This happens while I was putting verse chapter/topic headings. on Matthew 13.  Aborting doesn't fix it and it appears when restarting the program. What's weird is the context panel only shows till verse 16 where the error occurs. The chapter has 58 verses. Also the error didn't happen with Chapters 1 through 12.

![image](https://user-images.githubusercontent.com/46296587/89482812-3e32b700-d7cd-11ea-9d3e-c3b75046e7f5.png)

**Comment by rubiot** [comment]
Good day, sir. This error occurs when iBiblia tries to render the chapter view. Looking at the screenshot it looks like you have some line breaks in your title. iBiblia does not account for that. If that's the case, here are some options that may help you get rid of that problem until a fix is made:
1. If it's possible to close the error dialog and get back to to iBiblia, edit your title to remove the line breaks;
2. If that's not possible, you can close iBiblia, open iBiblia.ini file, find the line `chapter.view.text=<some number>` and change it to any other number from 0 to 3. Save it and reopen iBiblia. This time it should render OK, because it will render another text. Now you can fix your header and you should be good to go.

**Comment by openbibles** [comment]
It's that line break!
Thanks bro.
Edmund

**Comment by rubiot** [comment]
I assume you pasted that heading text, right? Because the verse edit box should be blocking the ENTER key.

**Comment by openbibles** [comment]
Yes. I copied the heading from a 2 line heading in my document.

**Comment by rubiot** [comment]
OK. I reopen the issue and change its title so iBiblia can prevent this from happening again.

**Comment by rubiot** [comment]
Fixed. The changes will be available in the next release.
