### ISSUE TITLE
Program does not save previous pop-up dictionary zoom level

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#9]

**Comment by malayangbiblia** [comment]
If you don't mind, I would suggest that you just drop this pop up feature because theWord already has it. Or have a switch to turn this feature off if users prefer esp when using both this and theWord at the same time. The sync feature works wonders, I tell you. If the sync is on, its as if iBiblia becomes part of TheWord just on a separate window. iBiblia becomes the master and theWord, the slave. theWord gives iBiblia whatever it needs from its vast array of features!

**Comment by rubiot** [comment]
Just leave the dicionary fields empty in the project properties dialog and you'll never see the popup again. :)

theWord works fine when you only have Strong's tags. When you also have morphology tags you'll need the popup, because there's no way to synchronize both definitions on theWord.

**Comment by rubiot** [comment]
This was fixed, but I replaced the RTF component after that (to support Linux) and had to re-implement the zoom feature. The zoom level now is saved, but it does not work the first time the popup is displayed :(. I'll keep this open until I fix that. Until there, the workaround is to hide the popup and bring it up again every time you open iBiblia...
Please check the new [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.61).

**Comment by openbibles** [comment]
Awesome! I didn't notice that bug, though. It looks better now w/ background color!

**Comment by openbibles** [comment]
If you may also fix the Translation memory zoom so that its not too eye straining caused by looking abruptly from a larger text to the default size one. Thanks!

**Comment by openbibles** [comment]
Hi Rubio, I think this is already fixed and can be closed. Don't you think so?

**Comment by rubiot** [comment]
Great!
