### ISSUE TITLE
Exporting removes any space next to the string <WG????

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#93]
I'm in the process of making additional Strong's codes (For the LXX) using one of the TW dictionary files. My additional entries look like the ff:

G5673 - ἀπαλείφω, ἀπαλείψω
G5674 - ἀσφαλτόω, ἀσφαλτώσεις
G5675 - ασφαλτω, ἄσφαλτος

So my source text has a string like these, <wt>ἀπαλείψω<WG5673 - ἀπαλείφω, ἀπαλείψω><WTV-FAI-1S>       (from LXX Gen. 6:7)

After exporting the associations, the above string will look like this, <wt>ἀπαλείψω<WG5673- ἀπαλείφω, ἀπαλείψω><WTV-FAI-1S>

So, it deletes the space between WG5673 and - ἀπαλείφω
As a result the dictionary entry won't pop up on iBiblia or in TW.

You can download my dictionary here: https://1drv.ms/u/s!As-j6IT9oksXhclAODPQ-gs3NRb90A?e=8OSUkY
One of my working iBiblia files: https://1drv.ms/u/s!As-j6IT9oksXhb1Z84H4mTFoU8Vegw?e=JxnsBh

**Comment by rubiot** [comment]
Hi, Edmund! The problem here is that you introduced an invalid syntax. The Bible file must be in a valid theWord format (https://www.theword.net/docs/tw3-bible-module-spec.doc). Strong's tags must not have any additional information. If you want to indicate the lemma, it should go into the morphology tag instead, like this: `Μωὰβ<WG5866><WTN-ASM l="Μωὰβ">`

**Comment by openbibles** [comment]
Oh, I see! Thanks
