### ISSUE TITLE
Strong's dictionary with meta...

### ISSUE THREAD

**Issue by jonathangkoehn** [rubiot/ibiblia#99]
Would it be possible to include the support of meta tags that are in some Dictionaries. 
For example try AMGL dictionary and then hover a word with Strong's

**Comment by rubiot** [comment]
Well, I don't know if it's worth the time working on dictionary support, considering iBiblia can be synchronized with theWord and take advantage of all its power.

A setup that works very well for me is to keep theWord maximized with iBiblia always on top over an irrelevant area.

A side note: the new release of iBiblia does not accept a dictionary like AMGL anymore, because it uses RVF, iBiblia works with RTF/unencrypted/uncompressed dicionaries only.

**Comment by jonathangkoehn** [comment]
Thanks for the help I need to get back into the groove of iBiblia
